language: python
install:
  - pip install tox
script:
  - tox
notifications:
  slack:
    rooms:
      secure: S3P1Jl31EgYLFExIvlRWkmLZup11YpugwK16zqm3gM272URjjtPDS+tmHxgVpQ00x/qKHKp/VLwmyqHzO3a+sIIkNWoSuC2E5YMCgjJRBFDrgkq6OHWPk/Ra/8nDw0UIex8XBZR2XSr3e5NtLXl/Io45qtuk4KTdCLa/p8FyciA7B1IogU4VV7knnpaIfeRTZcDgwjbklbktMvgZ6/fl4+iLe+nCH5Cln9iObtzkUcSWaxz1ddDO0T3KlXP8ZDyFJZHRszWyHw7G0O3lGq1/tKV7ca8NZYyy/hwqo7jEbc8Ev5NJOoCHmvjms9qIPg6h3zP5RbM6595TRooXbJI+5t9+htoIPQjcBMECfIAJ6WY1tTZ+BlWvrKDmA3BD57z6JoY+7tWj33+YPC0t2Jj6kfe3fHxTgjIB/McOq9y0xTPyRbM9dC+RnefhUMzIgd4cYGGJp2vrly2uWL+Psamr2dBd4SiDjQEvrC6niR6kMed2MVmFCEGe/A4gg6E+rdOHxjXQn9Vhbb0Zkbs2B/SPauTaTIGwfnYqccGUl7cQk9Fq5nLWZr4kVtz71U+tyg3czYjagmVBn/8NEz9Vk4n1sAsV7EXSUkBVmYs+rpWVCLtNAfJJucIPZn4qUnZ4qsLcHIp1O9CVhGJe/m11FG6bJsrEmWeF7/pi+XfEr5G940A=
    on_start: always
    on_failure: always
    on_success: always
